name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt', 'pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps + project (editable)
        run: |
          python -m pip install -U pip
          pip install -U "setuptools>=68" wheel
          pip install -r requirements-dev.txt
          pip install -e .               

      # Optional: quick import smoke check
      - name: Verify package import
        run: |
          python - <<'PY'
          import transforms, sys
          print("transforms path:", getattr(transforms, "__file__", "n/a"))
          print("python:", sys.version)
          PY

      - name: Run tests
        env:
          PYSPARK_PYTHON: python
          PYSPARK_DRIVER_PYTHON: python
        run: |
          pytest -q -m "not contract" --durations=10 --cov --cov-report=term-missing