name: Contract
on:
  schedule:
    - cron: "21 2 * * *"   # daily UTC
  workflow_dispatch:

permissions:
  id-token: write   # OIDC
  contents: read

jobs:
  contract:
    # Only run when enabled in repo variables - disabled by default to avoid initial cost
    if: ${{ vars.ENABLE_CONTRACT == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.GH_OIDC_ROLE }}
          aws-region: us-east-1
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run contract tests
        env:
          WISTIA_SECRET_ARN: ${{ vars.WISTIA_SECRET_ARN }}
        run: |
          pytest -q -m contract