name: Contract
on:
  schedule:
    - cron: "21 2 * * *"   # daily UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  contract:
    if: ${{ vars.ENABLE_CONTRACT == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: "3.10" }   # match your CI/python locally

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements-dev.txt
          pip install -e .

      - name: Run contract tests
        env:
          WISTIA_API_TOKEN: ${{ secrets.WISTIA_API_TOKEN }}
          MEDIA_IDS: ${{ secrets.WISTIA_MEDIA_ID_1 }}
          PYSPARK_PYTHON: python
          PYSPARK_DRIVER_PYTHON: python
        run: |
          pytest -q -m contract
